import React, { useState, useRef, useCallback } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  Alert,
  TextInput,
  Share,
  Platform,
  ActivityIndicator,
  Modal,
  KeyboardAvoidingView,
  PanResponder,
  Animated,
  LayoutChangeEvent,
} from 'react-native';
import { File, Paths } from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import * as Clipboard from 'expo-clipboard';
import { useApp } from '../context/AppContext';
import StatsBar from '../components/StatsBar';
import AlertsList from '../components/AlertsList';
import ScheduleView from '../components/ScheduleView';
import MedicationCard from '../components/MedicationCard';
import AutocompleteInput from '../components/AutocompleteInput';
import PatientSelectorModal from '../components/PatientSelectorModal';
import { COMMON_ALLERGENS, fetchAllergySuggestions, fetchDrugSuggestions } from '../services/rxnorm';
import { checkInteractions, CRITICAL_INTERACTIONS } from '../services/interactions';
import { Interaction, Medication } from '../types';

export default function HomeScreen({ navigation }: any) {
  const {
    patients,
    currentPatient,
    setCurrentPatient,
    addPatient,
    renamePatient,
    reorderPatients,
    deleteMedication,
    addAllergy,
    deleteAllergy,
    updatePatientNotes,
    getCurrentPatient,
    interactions,
    allergyConflicts,
  } = useApp();

  const patient = getCurrentPatient();
  const [showAllergyInput, setShowAllergyInput] = useState(false);
  const [allergyText, setAllergyText] = useState('');
  const [showNotes, setShowNotes] = useState(false);

  const handleAddAllergy = () => {
    if (allergyText.trim()) {
      addAllergy(allergyText.trim());
      setAllergyText('');
      setShowAllergyInput(false);
    }
  };

  const handleDeleteAllergy = (id: number) => {
    Alert.alert('Remove Allergy', 'Remove this allergy?', [
      { text: 'Cancel', style: 'cancel' },
      { text: 'Remove', style: 'destructive', onPress: () => deleteAllergy(id) },
    ]);
  };

  const buildMedList = () => {
    const medications = patient.medications || [];
    const allergies = patient.allergies || [];

    let text = `MEDICATION LIST\n`;
    text += `Patient: ${patient.name}\n`;
    text += `Date: ${new Date().toLocaleDateString()}\n\n`;

    if (allergies.length > 0) {
      text += `ALLERGIES:\n`;
      allergies.forEach((a) => (text += `  - ${a.name}\n`));
      text += '\n';
    }

    text += `CURRENT MEDICATIONS:\n${'='.repeat(50)}\n\n`;

    medications.forEach((med, i) => {
      text += `${i + 1}. ${med.name}\n`;
      text += `   Dosage: ${med.dosage}\n`;
      text += `   Frequency: ${med.frequency}\n`;
      if (med.doctor) text += `   Prescribing Doctor: Dr. ${med.doctor}\n`;
      if (med.reason) text += `   For: ${med.reason}\n`;
      if (med.refillDate) {
        const daysUntil = Math.ceil(
          (new Date(med.refillDate).getTime() - Date.now()) / (1000 * 60 * 60 * 24)
        );
        text += `   Next Refill: ${new Date(med.refillDate).toLocaleDateString()}`;
        if (daysUntil <= 7 && daysUntil >= 0) text += ` (${daysUntil} days)`;
        text += '\n';
      }
      text += '\n';
    });

    text += `\nGenerated by MedGuardian\n${new Date().toLocaleString()}\n`;
    return text;
  };

  const buildClinicalDoc = (notes?: string) => {
    const medications = patient.medications || [];
    const allergies = patient.allergies || [];

    let text = `MEDICATION RECONCILIATION\n`;
    text += `Date: ${new Date().toLocaleDateString()}\n`;
    text += `Patient: ${patient.name}\n\n`;

    text += `ALLERGIES:\n`;
    if (allergies.length > 0) {
      allergies.forEach((a) => (text += `- ${a.name}\n`));
    } else {
      text += `No known drug allergies\n`;
    }
    text += '\n';

    text += `CURRENT MEDICATIONS:\n`;
    medications.forEach((med, i) => {
      let line = `${i + 1}. ${med.name} ${med.dosage} - ${med.frequency}`;
      if (med.doctor) line += ` - Prescribed by Dr. ${med.doctor}`;
      text += `${line}\n`;
      if (med.reason) text += `   Indication: ${med.reason}\n`;
      text += '\n';
    });

    if (interactions.length > 0) {
      text += `DRUG INTERACTIONS IDENTIFIED:\n`;
      interactions.forEach((ix) => {
        text += `- ${ix.med1} + ${ix.med2}: ${ix.severity.toUpperCase()} - ${ix.description}\n`;
      });
    } else {
      text += `DRUG INTERACTIONS IDENTIFIED:\n`;
      text += `No significant interactions identified\n`;
    }
    text += '\n';

    text += `NOTES:\n`;
    text += notes?.trim() ? `${notes.trim()}\n` : `(No notes added)\n`;
    text += '\n';
    text += `Documented using MedGuardian medication tracking tool\n`;
    return text;
  };

  const shareText = async (text: string, fileName: string) => {
    try {
      if (Platform.OS === 'web') {
        await Share.share({ message: text });
      } else {
        const file = new File(Paths.cache, fileName);
        file.write(text);
        if (await Sharing.isAvailableAsync()) {
          await Sharing.shareAsync(file.uri, { mimeType: 'text/plain' });
        } else {
          await Share.share({ message: text });
        }
      }
    } catch {
      await Share.share({ message: text });
    }
  };

  // Share modal
  const [showShareModal, setShowShareModal] = useState(false);
  const [shareMode, setShareMode] = useState<'patient' | 'clinical'>('patient');

  const handleShareMenu = () => {
    const medications = patient.medications || [];
    if (medications.length === 0) {
      Alert.alert('No Medications', 'No medications to share.');
      return;
    }
    setShareMode('clinical');
    setShowShareModal(true);
  };

  const handleShareAction = async (action: 'share' | 'copy') => {
    const dateSuffix = new Date().toISOString().split('T')[0];
    const safeName = patient.name.replace(/\s/g, '-');
    const text = shareMode === 'clinical'
      ? buildClinicalDoc(patient.notes)
      : buildMedList();
    const fileName = shareMode === 'clinical'
      ? `med-reconciliation-${safeName}-${dateSuffix}.txt`
      : `meds-${safeName}-${dateSuffix}.txt`;

    setShowShareModal(false);

    if (action === 'copy') {
      await Clipboard.setStringAsync(text);
      Alert.alert('Copied', `${shareMode === 'clinical' ? 'Clinical documentation' : 'Medication list'} copied to clipboard.`);
    } else {
      await shareText(text, fileName);
    }
  };

  // Interaction checker
  const [showInteractionCheck, setShowInteractionCheck] = useState(false);
  const [checkDrugName, setCheckDrugName] = useState('');
  const [checkResults, setCheckResults] = useState<Interaction[] | null>(null);
  const [checkLoading, setCheckLoading] = useState(false);

  const handleInteractionCheck = async () => {
    const drugName = checkDrugName.trim();
    if (!drugName) return;
    if (patient.medications.length === 0) {
      Alert.alert('No Medications', 'Add medications first to check for interactions.');
      return;
    }

    setCheckLoading(true);
    try {
      // Create a temporary medication to check against the current list
      const tempMed: Medication = {
        id: -1,
        name: drugName,
        dosage: '',
        frequency: '',
        doctor: '',
        reason: '',
        refillDate: null,
        addedDate: new Date().toISOString(),
        schedule: 'morning',
      };
      const allMeds = [...patient.medications, tempMed];
      const results = await checkInteractions(allMeds);
      // Filter to only interactions involving the checked drug
      const relevant = results.filter(
        (r) => r.med1.toLowerCase() === drugName.toLowerCase() || r.med2.toLowerCase() === drugName.toLowerCase()
      );
      setCheckResults(relevant);
    } catch {
      setCheckResults([]);
    } finally {
      setCheckLoading(false);
    }
  };

  // Patient rename on long-press
  const handleRenamePatient = (id: string, currentName: string) => {
    Alert.prompt
      ? Alert.prompt('Rename Patient', '', (newName) => {
          if (newName?.trim()) renamePatient(id, newName.trim());
        }, 'plain-text', currentName)
      : Alert.alert('Rename Patient', `Current name: ${currentName}`, [
          { text: 'Cancel', style: 'cancel' },
          {
            text: 'Rename',
            onPress: () => {
              setRenamingPatientId(id);
              setRenamingPatientText(currentName);
            },
          },
        ]);
  };
  const [renamingPatientId, setRenamingPatientId] = useState<string | null>(null);
  const [renamingPatientText, setRenamingPatientText] = useState('');


  // Patient selector with inline add
  const [newPatientName, setNewPatientName] = useState('');
  const [showNewPatient, setShowNewPatient] = useState(false);
  const [showPatientModal, setShowPatientModal] = useState(false);
  const patientCount = Object.keys(patients).length;

  // Drag-to-reorder state
  const [draggingId, setDraggingId] = useState<string | null>(null);
  const [dragOrder, setDragOrder] = useState<string[] | null>(null);
  const dragX = useRef(new Animated.Value(0)).current;
  const chipLayouts = useRef<Record<string, { x: number; width: number }>>({});
  const longPressTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const isDragging = useRef(false);

  const handleChipLayout = useCallback((id: string, e: LayoutChangeEvent) => {
    const { x, width } = e.nativeEvent.layout;
    chipLayouts.current[id] = { x, width };
  }, []);

  const panResponder = useRef(
    PanResponder.create({
      onStartShouldSetPanResponder: () => false,
      onMoveShouldSetPanResponder: (_, gs) => {
        // Only capture if we're in drag mode (long hold triggered) and moved enough
        return isDragging.current && Math.abs(gs.dx) > 5;
      },
      onPanResponderGrant: () => {},
      onPanResponderMove: (_, gs) => {
        if (!isDragging.current) return;
        dragX.setValue(gs.dx);

        // Calculate reorder based on position
        const currentIds = dragOrder ?? Object.keys(patients);
        const dragIdx = draggingId ? currentIds.indexOf(draggingId) : -1;
        if (dragIdx < 0 || !draggingId) return;

        const dragLayout = chipLayouts.current[draggingId];
        if (!dragLayout) return;
        const currentCenter = dragLayout.x + dragLayout.width / 2 + gs.dx;

        // Check if we've crossed into a neighbor's territory
        for (let i = 0; i < currentIds.length; i++) {
          if (i === dragIdx) continue;
          const layout = chipLayouts.current[currentIds[i]];
          if (!layout) continue;
          const center = layout.x + layout.width / 2;

          if (i < dragIdx && currentCenter < center) {
            const newOrder = [...currentIds];
            newOrder.splice(dragIdx, 1);
            newOrder.splice(i, 0, draggingId);
            setDragOrder(newOrder);
            break;
          } else if (i > dragIdx && currentCenter > center) {
            const newOrder = [...currentIds];
            newOrder.splice(dragIdx, 1);
            newOrder.splice(i, 0, draggingId);
            setDragOrder(newOrder);
            break;
          }
        }
      },
      onPanResponderRelease: () => {
        if (isDragging.current && dragOrder) {
          reorderPatients(dragOrder);
        }
        isDragging.current = false;
        setDraggingId(null);
        setDragOrder(null);
        dragX.setValue(0);
        if (longPressTimer.current) {
          clearTimeout(longPressTimer.current);
          longPressTimer.current = null;
        }
      },
      onPanResponderTerminate: () => {
        isDragging.current = false;
        setDraggingId(null);
        setDragOrder(null);
        dragX.setValue(0);
        if (longPressTimer.current) {
          clearTimeout(longPressTimer.current);
          longPressTimer.current = null;
        }
      },
    })
  ).current;

  const startDragTimer = useCallback((id: string) => {
    if (longPressTimer.current) clearTimeout(longPressTimer.current);
    // Long hold (800ms) starts drag mode — shorter hold (500ms) will trigger rename via onLongPress
    longPressTimer.current = setTimeout(() => {
      isDragging.current = true;
      setDraggingId(id);
      setDragOrder(Object.keys(patients));
      dragX.setValue(0);
    }, 800);
  }, [patients]);

  const cancelDragTimer = useCallback(() => {
    if (longPressTimer.current) {
      clearTimeout(longPressTimer.current);
      longPressTimer.current = null;
    }
  }, []);

  return (
    <View style={{ flex: 1 }}>
    <ScrollView style={styles.container} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
      {/* Patient Selector */}
      {patientCount > 5 ? (
        <View style={styles.patientSection}>
          <TouchableOpacity style={styles.patientDropdownBtn} onPress={() => setShowPatientModal(true)}>
            <Text style={styles.patientDropdownText}>{patient.name}</Text>
            <Text style={styles.patientDropdownMeta}>
              {patientCount} patients
            </Text>
          </TouchableOpacity>
          <PatientSelectorModal
            visible={showPatientModal}
            onClose={() => setShowPatientModal(false)}
            patients={patients}
            currentPatient={currentPatient}
            onSelectPatient={(id) => { setCurrentPatient(id); setShowPatientModal(false); }}
            onAddPatient={(name) => { addPatient(name); setShowPatientModal(false); }}
            onRenamePatient={renamePatient}
          />
        </View>
      ) : (
        <View style={styles.patientSection}>
          <ScrollView
            horizontal
            showsHorizontalScrollIndicator={false}
            style={styles.patientScroll}
            scrollEnabled={!draggingId}
          >
            <View style={styles.chipRow} {...panResponder.panHandlers}>
              {(dragOrder ?? Object.keys(patients)).map((id) => {
                const p = patients[id];
                if (!p) return null;
                const isBeingDragged = draggingId === id;
                return (
                  <Animated.View
                    key={id}
                    onLayout={(e) => handleChipLayout(id, e)}
                    style={[
                      isBeingDragged && {
                        transform: [{ translateX: dragX }],
                        zIndex: 10,
                        opacity: 0.85,
                        elevation: 4,
                        shadowColor: '#000',
                        shadowOffset: { width: 0, height: 2 },
                        shadowOpacity: 0.25,
                        shadowRadius: 4,
                      },
                      draggingId && !isBeingDragged && { opacity: 0.5 },
                    ]}
                  >
                    <TouchableOpacity
                      style={[
                        styles.patientChip,
                        id === currentPatient && styles.patientChipActive,
                        isBeingDragged && styles.patientChipDragging,
                      ]}
                      onPress={() => { if (!draggingId) setCurrentPatient(id); }}
                      onLongPress={() => { if (!isDragging.current) handleRenamePatient(id, p.name); }}
                      delayLongPress={500}
                      onPressIn={() => startDragTimer(id)}
                      onPressOut={() => { if (!isDragging.current) cancelDragTimer(); }}
                      activeOpacity={0.7}
                    >
                      <Text style={[styles.patientChipText, id === currentPatient && styles.patientChipTextActive]}>
                        {p.name}
                      </Text>
                      {isBeingDragged && (
                        <Text style={styles.dragHint}>&#x2630;</Text>
                      )}
                    </TouchableOpacity>
                  </Animated.View>
                );
              })}
              <TouchableOpacity style={styles.addPatientChip} onPress={() => setShowNewPatient(true)}>
                <Text style={styles.addPatientText}>+ Add</Text>
              </TouchableOpacity>
            </View>
          </ScrollView>

          {/* Inline rename input (Android fallback — no Alert.prompt) */}
          {renamingPatientId && (
            <View style={styles.newPatientRow}>
              <TextInput
                style={styles.newPatientInput}
                placeholder="New name..."
                value={renamingPatientText}
                onChangeText={setRenamingPatientText}
                autoFocus
                onSubmitEditing={() => {
                  if (renamingPatientText.trim()) renamePatient(renamingPatientId, renamingPatientText.trim());
                  setRenamingPatientId(null);
                }}
              />
              <TouchableOpacity
                style={styles.newPatientSave}
                onPress={() => {
                  if (renamingPatientText.trim()) renamePatient(renamingPatientId, renamingPatientText.trim());
                  setRenamingPatientId(null);
                }}
              >
                <Text style={styles.newPatientSaveText}>Save</Text>
              </TouchableOpacity>
              <TouchableOpacity onPress={() => setRenamingPatientId(null)}>
                <Text style={{ color: '#a0aec0', fontSize: 16, marginLeft: 10 }}>Cancel</Text>
              </TouchableOpacity>
            </View>
          )}

          {showNewPatient && (
            <View style={styles.newPatientRow}>
              <TextInput
                style={styles.newPatientInput}
                placeholder="Patient name..."
                value={newPatientName}
                onChangeText={setNewPatientName}
                autoFocus
              />
              <TouchableOpacity
                style={styles.newPatientSave}
                onPress={() => {
                  if (newPatientName.trim()) {
                    addPatient(newPatientName.trim());
                    setNewPatientName('');
                    setShowNewPatient(false);
                  }
                }}
              >
                <Text style={styles.newPatientSaveText}>Add</Text>
              </TouchableOpacity>
              <TouchableOpacity onPress={() => { setShowNewPatient(false); setNewPatientName(''); }}>
                <Text style={{ color: '#a0aec0', fontSize: 16, marginLeft: 10 }}>Cancel</Text>
              </TouchableOpacity>
            </View>
          )}
        </View>
      )}

      {/* Allergies */}
      <View style={styles.allergySection}>
        <View style={styles.allergyHeader}>
          <Text style={styles.allergyTitle}>Allergies</Text>
          <TouchableOpacity style={styles.addAllergyBtn} onPress={() => setShowAllergyInput(true)}>
            <Text style={styles.addAllergyText}>+ Add Allergy</Text>
          </TouchableOpacity>
        </View>

        {showAllergyInput && (
          <AutocompleteInput
            value={allergyText}
            onChangeText={setAllergyText}
            onSubmit={handleAddAllergy}
            placeholder="Type an allergy..."
            localSuggestions={COMMON_ALLERGENS}
            fetchSuggestions={fetchAllergySuggestions}
            accentColor="#fc8181"
            autoFocus
          />
        )}

        {(patient.allergies || []).length === 0 ? (
          <Text style={styles.emptyAllergy}>No allergies recorded</Text>
        ) : (
          patient.allergies.map((allergy) => (
            <View key={allergy.id} style={styles.allergyItem}>
              <Text style={styles.allergyName}>{allergy.name}</Text>
              <TouchableOpacity onPress={() => handleDeleteAllergy(allergy.id)}>
                <Text style={styles.allergyDelete}>x</Text>
              </TouchableOpacity>
            </View>
          ))
        )}
      </View>

      {/* Provider Notes */}
      <View style={styles.notesSection}>
        <TouchableOpacity
          style={styles.notesHeader}
          onPress={() => setShowNotes(!showNotes)}
          activeOpacity={0.7}
        >
          <Text style={styles.notesTitle}>Notes</Text>
          <Text style={styles.notesToggle}>{showNotes ? '−' : '+'}</Text>
        </TouchableOpacity>
        {showNotes && (
          <TextInput
            style={styles.notesInput}
            placeholder="Add clinical notes, follow-up instructions, observations..."
            value={patient.notes || ''}
            onChangeText={updatePatientNotes}
            multiline
            textAlignVertical="top"
          />
        )}
        {!showNotes && patient.notes?.trim() ? (
          <Text style={styles.notesPreview} numberOfLines={2}>{patient.notes.trim()}</Text>
        ) : null}
      </View>

      {/* Stats */}
      <StatsBar />

      {/* Alerts */}
      <AlertsList />

      {/* Schedule */}
      <ScheduleView
        medications={patient.medications}
        onPressMedication={(med) => navigation.navigate('MedicationDetail', { medication: med })}
      />

      {/* Add Medication Button */}
      <TouchableOpacity
        style={styles.addMedBtn}
        onPress={() => navigation.navigate('AddMedication')}
        activeOpacity={0.8}
      >
        <Text style={styles.addMedBtnIcon}>+</Text>
        <Text style={styles.addMedBtnText}>Add Medication</Text>
      </TouchableOpacity>

      {/* Interaction Checker */}
      {patient.medications.length > 0 && (
        <View style={styles.interactionCheckSection}>
          <TouchableOpacity
            style={styles.interactionCheckToggle}
            onPress={() => {
              setShowInteractionCheck(!showInteractionCheck);
              setCheckResults(null);
              setCheckDrugName('');
            }}
          >
            <Text style={styles.interactionCheckToggleText}>
              {showInteractionCheck ? '- Hide' : '+ Check'} Drug Interactions
            </Text>
          </TouchableOpacity>

          {showInteractionCheck && (
            <View style={styles.interactionCheckBody}>
              <Text style={styles.interactionCheckHint}>
                Type a drug name to check for interactions with current medications
              </Text>
              <View style={{ zIndex: 10 }}>
                <AutocompleteInput
                  value={checkDrugName}
                  onChangeText={(text) => { setCheckDrugName(text); setCheckResults(null); }}
                  placeholder="e.g., Warfarin, Ibuprofen..."
                  fetchSuggestions={fetchDrugSuggestions}
                  accentColor="#e2e8f0"
                  showSubmitButton={false}
                  inputStyle={styles.interactionCheckInput}
                />
              </View>
              <TouchableOpacity
                style={[styles.interactionCheckBtn, !checkDrugName.trim() && { opacity: 0.5 }]}
                onPress={handleInteractionCheck}
                disabled={!checkDrugName.trim() || checkLoading}
              >
                {checkLoading ? (
                  <ActivityIndicator size="small" color="#fff" />
                ) : (
                  <Text style={styles.interactionCheckBtnText}>Check Interactions</Text>
                )}
              </TouchableOpacity>

              {checkResults !== null && (
                <View style={styles.interactionCheckResults}>
                  {checkResults.length === 0 ? (
                    <View style={styles.interactionCheckSafe}>
                      <Text style={styles.interactionCheckSafeText}>
                        No interactions found between {checkDrugName} and current medications.
                      </Text>
                    </View>
                  ) : (
                    checkResults.map((ix, i) => (
                      <View
                        key={i}
                        style={[
                          styles.interactionCheckItem,
                          ix.severity === 'major' && styles.interactionCheckMajor,
                        ]}
                      >
                        <Text style={styles.interactionCheckSeverity}>
                          {ix.severity.toUpperCase()}
                        </Text>
                        <Text style={styles.interactionCheckPair}>
                          {ix.med1} + {ix.med2}
                        </Text>
                        <Text style={styles.interactionCheckDesc}>{ix.description}</Text>
                        {ix.info ? (
                          <Text style={styles.interactionCheckInfo}>{ix.info}</Text>
                        ) : null}
                      </View>
                    ))
                  )}
                  <View style={styles.verifyPrompt}>
                    <Text style={styles.verifyPromptText}>
                      Always verify interactions with your pharmacist or at drugs.com/interaction-checker. This is not a complete database.
                    </Text>
                  </View>
                </View>
              )}
            </View>
          )}
        </View>
      )}

      {/* Medications List */}
      <View style={styles.medsHeader}>
        <Text style={styles.medsTitle}>Current Medications</Text>
        {patient.medications.length > 0 && (
          <TouchableOpacity style={styles.shareBtn} onPress={handleShareMenu}>
            <Text style={styles.shareBtnText}>Share List</Text>
          </TouchableOpacity>
        )}
      </View>

      {patient.medications.length === 0 ? (
        <View style={styles.emptyState}>
          <Text style={styles.emptyText}>No medications added yet</Text>
          <Text style={styles.emptySubText}>
            Tap "Add Medication" above to get started
          </Text>
        </View>
      ) : (
        patient.medications.map((med) => (
          <MedicationCard
            key={med.id}
            medication={med}
            interactions={interactions}
            allergyConflicts={allergyConflicts}
            onDelete={deleteMedication}
            onPress={() => navigation.navigate('MedicationDetail', { medication: med })}
          />
        ))
      )}

      <Text style={styles.footer}>* This app displays general medication information from public databases. Not medical advice. Consult your healthcare provider.</Text>

      <View style={{ height: 20 }} />
    </ScrollView>

    {/* Share Modal */}
    <Modal visible={showShareModal} animationType="slide" transparent>
      <KeyboardAvoidingView
        style={styles.shareOverlay}
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      >
        <TouchableOpacity
          style={styles.shareBackdrop}
          activeOpacity={1}
          onPress={() => setShowShareModal(false)}
        />
        <View style={styles.shareSheet}>
          <View style={styles.shareHandle} />
          <Text style={styles.shareTitle}>Share Medication List</Text>

          {/* Format toggle */}
          <View style={styles.shareModeRow}>
            <TouchableOpacity
              style={[styles.shareModeBtn, shareMode === 'clinical' && styles.shareModeBtnActive]}
              onPress={() => setShareMode('clinical')}
            >
              <Text style={[styles.shareModeText, shareMode === 'clinical' && styles.shareModeTextActive]}>
                Clinical / EMR
              </Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={[styles.shareModeBtn, shareMode === 'patient' && styles.shareModeBtnActive]}
              onPress={() => setShareMode('patient')}
            >
              <Text style={[styles.shareModeText, shareMode === 'patient' && styles.shareModeTextActive]}>
                Patient List
              </Text>
            </TouchableOpacity>
          </View>
          <Text style={styles.shareModeDesc}>
            {shareMode === 'clinical'
              ? `Includes interactions and reconciliation format${patient.notes?.trim() ? ' (notes included)' : ''}`
              : 'Simple list for the patient or caregiver'}
          </Text>

          {/* Action buttons */}
          <View style={styles.shareActions}>
            <TouchableOpacity
              style={styles.shareActionBtn}
              onPress={() => handleShareAction('share')}
            >
              <Text style={styles.shareActionText}>Share File</Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={styles.shareCopyBtn}
              onPress={() => handleShareAction('copy')}
            >
              <Text style={styles.shareCopyText}>Copy to Clipboard</Text>
            </TouchableOpacity>
          </View>

          <TouchableOpacity
            style={styles.shareCancelBtn}
            onPress={() => setShowShareModal(false)}
          >
            <Text style={styles.shareCancelText}>Cancel</Text>
          </TouchableOpacity>
        </View>
      </KeyboardAvoidingView>
    </Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f7fa' },
  content: { padding: 16 },
  footer: { fontSize: 11, color: '#a0aec0', textAlign: 'center', marginTop: 20, paddingHorizontal: 10 },
  patientSection: { marginBottom: 16 },
  patientScroll: { flexDirection: 'row' },
  chipRow: { flexDirection: 'row', alignItems: 'center' },
  patientChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: '#e2e8f0',
    marginRight: 8,
  },
  patientChipActive: { backgroundColor: '#667eea' },
  patientChipDragging: {
    borderWidth: 2,
    borderColor: '#4c63d2',
    borderStyle: 'dashed',
  },
  patientChipText: { fontSize: 14, color: '#4a5568' },
  patientChipTextActive: { color: '#fff', fontWeight: '600' },
  dragHint: { fontSize: 12, color: 'rgba(255,255,255,0.7)', marginLeft: 4 },
  addPatientChip: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#cbd5e0',
    borderStyle: 'dashed',
  },
  addPatientText: { fontSize: 14, color: '#667eea' },
  newPatientRow: { flexDirection: 'row', alignItems: 'center', marginTop: 10 },
  newPatientInput: {
    flex: 1,
    borderWidth: 2,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    padding: 10,
    fontSize: 14,
    backgroundColor: '#fff',
  },
  newPatientSave: {
    backgroundColor: '#667eea',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginLeft: 8,
  },
  newPatientSaveText: { color: '#fff', fontWeight: '600' },
  allergySection: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  allergyHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  allergyTitle: { fontWeight: '600', fontSize: 14, color: '#4a5568' },
  addAllergyBtn: { backgroundColor: '#fc8181', paddingVertical: 6, paddingHorizontal: 12, borderRadius: 6 },
  addAllergyText: { color: '#fff', fontSize: 12, fontWeight: '600' },
  allergyInputRow: { flexDirection: 'row', marginBottom: 10 },
  allergyInput: {
    flex: 1,
    borderWidth: 2,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    padding: 10,
    fontSize: 14,
  },
  allergyInputSave: {
    backgroundColor: '#fc8181',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginLeft: 8,
    justifyContent: 'center',
  },
  emptyAllergy: { color: '#a0aec0', fontStyle: 'italic', fontSize: 13 },
  allergyItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 8,
    backgroundColor: '#fff5f5',
    borderWidth: 1,
    borderColor: '#fc8181',
    borderRadius: 6,
    marginBottom: 6,
  },
  allergyName: { color: '#c53030', fontWeight: '600', fontSize: 14 },
  allergyDelete: { color: '#fc8181', fontSize: 18, paddingHorizontal: 8 },
  medsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  medsTitle: { fontSize: 18, fontWeight: '700', color: '#2d3748' },
  shareBtn: { backgroundColor: '#48bb78', paddingVertical: 8, paddingHorizontal: 16, borderRadius: 8 },
  shareBtnText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  emptyState: { alignItems: 'center', padding: 40 },
  emptyText: { fontSize: 16, color: '#a0aec0', marginBottom: 8 },
  emptySubText: { fontSize: 14, color: '#cbd5e0', textAlign: 'center' },
  addMedBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#667eea',
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
    gap: 8,
    elevation: 2,
    shadowColor: '#667eea',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  addMedBtnIcon: { color: '#fff', fontSize: 22, fontWeight: '700' },
  addMedBtnText: { color: '#fff', fontSize: 17, fontWeight: '700' },
  patientDropdownBtn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#667eea',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
  },
  patientDropdownText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  patientDropdownMeta: { color: 'rgba(255,255,255,0.7)', fontSize: 13 },
  interactionCheckSection: {
    marginBottom: 20,
  },
  interactionCheckToggle: {
    backgroundColor: '#fff',
    borderWidth: 2,
    borderColor: '#667eea',
    borderRadius: 10,
    padding: 12,
    alignItems: 'center',
  },
  interactionCheckToggleText: { color: '#667eea', fontSize: 15, fontWeight: '600' },
  interactionCheckBody: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    padding: 14,
    marginTop: 8,
  },
  interactionCheckHint: { fontSize: 13, color: '#718096', marginBottom: 10 },
  interactionCheckInput: {
    borderWidth: 2,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    backgroundColor: '#fff',
  },
  interactionCheckBtn: {
    backgroundColor: '#667eea',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 10,
  },
  interactionCheckBtnText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  interactionCheckResults: { marginTop: 12 },
  interactionCheckSafe: {
    backgroundColor: '#f0fff4',
    borderWidth: 1,
    borderColor: '#48bb78',
    borderRadius: 8,
    padding: 14,
  },
  interactionCheckSafeText: { color: '#276749', fontSize: 14 },
  interactionCheckItem: {
    backgroundColor: '#fffaf0',
    borderWidth: 1,
    borderColor: '#ed8936',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
  },
  interactionCheckMajor: {
    backgroundColor: '#fff5f5',
    borderColor: '#e53e3e',
  },
  interactionCheckSeverity: {
    fontSize: 11,
    fontWeight: '700',
    color: '#c53030',
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  interactionCheckPair: { fontSize: 14, fontWeight: '600', color: '#2d3748', marginBottom: 4 },
  interactionCheckDesc: { fontSize: 13, color: '#4a5568', marginBottom: 4 },
  interactionCheckInfo: { fontSize: 12, color: '#718096', fontStyle: 'italic' },
  verifyPrompt: {
    backgroundColor: '#ebf8ff',
    borderWidth: 1,
    borderColor: '#90cdf4',
    borderRadius: 8,
    padding: 12,
    marginTop: 8,
  },
  verifyPromptText: { fontSize: 12, color: '#2b6cb0', lineHeight: 18 },

  // Share modal
  shareOverlay: { flex: 1, justifyContent: 'flex-end' },
  shareBackdrop: { flex: 1 },
  shareSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingBottom: 30,
  },
  shareHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#e2e8f0',
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 16,
  },
  shareTitle: { fontSize: 18, fontWeight: '700', color: '#2d3748', marginBottom: 14 },
  shareModeRow: { flexDirection: 'row', gap: 8, marginBottom: 10 },
  shareModeBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#e2e8f0',
    alignItems: 'center',
  },
  shareModeBtnActive: { borderColor: '#667eea', backgroundColor: '#667eea' },
  shareModeText: { fontSize: 14, fontWeight: '600', color: '#4a5568' },
  shareModeTextActive: { color: '#fff' },
  shareModeDesc: { fontSize: 12, color: '#a0aec0', marginBottom: 14 },

  // Patient notes
  notesSection: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  notesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  notesTitle: { fontWeight: '600', fontSize: 14, color: '#4a5568' },
  notesToggle: { fontSize: 18, color: '#667eea', fontWeight: '700' },
  notesInput: {
    borderWidth: 2,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    minHeight: 100,
    backgroundColor: '#f7fafc',
    marginTop: 10,
  },
  notesPreview: {
    fontSize: 13,
    color: '#718096',
    marginTop: 6,
  },
  shareActions: { flexDirection: 'row', gap: 10, marginBottom: 10 },
  shareActionBtn: {
    flex: 1,
    backgroundColor: '#667eea',
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
  },
  shareActionText: { color: '#fff', fontSize: 15, fontWeight: '700' },
  shareCopyBtn: {
    flex: 1,
    borderWidth: 2,
    borderColor: '#667eea',
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
  },
  shareCopyText: { color: '#667eea', fontSize: 15, fontWeight: '600' },
  shareCancelBtn: { padding: 12, alignItems: 'center' },
  shareCancelText: { color: '#a0aec0', fontSize: 14, fontWeight: '600' },
});
