import React, { useState, useRef, useCallback } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  Alert,
  TextInput,
  Share,
  Platform,
  ActivityIndicator,
  Modal,
  KeyboardAvoidingView,
  PanResponder,
  Animated,
  LayoutChangeEvent,
} from 'react-native';
import { File, Paths } from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import * as Clipboard from 'expo-clipboard';
import { useApp } from '../context/AppContext';
import StatsBar from '../components/StatsBar';
import AlertsList from '../components/AlertsList';
import ScheduleView from '../components/ScheduleView';
import MedicationCard from '../components/MedicationCard';
import AutocompleteInput from '../components/AutocompleteInput';
import PatientSelectorModal from '../components/PatientSelectorModal';
import { COMMON_ALLERGENS, fetchAllergySuggestions, fetchDrugSuggestions } from '../services/rxnorm';
import { checkInteractions, CRITICAL_INTERACTIONS } from '../services/interactions';
import { Interaction, Medication } from '../types';

export default function HomeScreen({ navigation }: any) {
  const {
    patients,
    currentPatient,
    setCurrentPatient,
    addPatient,
    renamePatient,
    reorderPatients,
    deleteMedication,
    addAllergy,
    deleteAllergy,
    updatePatientNotes,
    addVisitNote,
    deleteVisitNote,
    getCurrentPatient,
    interactions,
    allergyConflicts,
  } = useApp();

  const patient = getCurrentPatient();
  const [showAllergyInput, setShowAllergyInput] = useState(false);
  const [allergyText, setAllergyText] = useState('');
  const [showNotes, setShowNotes] = useState(false);
  const [showVisitNotes, setShowVisitNotes] = useState(false);
  const [newVisitNote, setNewVisitNote] = useState('');
  const [showVisitInput, setShowVisitInput] = useState(false);

  const handleAddVisitNote = () => {
    if (newVisitNote.trim()) {
      addVisitNote(newVisitNote.trim());
      setNewVisitNote('');
      setShowVisitInput(false);
    }
  };

  const handleDeleteVisitNote = (id: number) => {
    Alert.alert('Delete Note', 'Remove this visit note?', [
      { text: 'Cancel', style: 'cancel' },
      { text: 'Delete', style: 'destructive', onPress: () => deleteVisitNote(id) },
    ]);
  };

  const formatVisitDate = (iso: string) => {
    const d = new Date(iso);
    const date = d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
    const time = d.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });
    return `${date} at ${time}`;
  };

  const handleAddAllergy = () => {
    if (allergyText.trim()) {
      addAllergy(allergyText.trim());
      setAllergyText('');
      setShowAllergyInput(false);
    }
  };

  const handleDeleteAllergy = (id: number) => {
    Alert.alert('Remove Allergy', 'Remove this allergy?', [
      { text: 'Cancel', style: 'cancel' },
      { text: 'Remove', style: 'destructive', onPress: () => deleteAllergy(id) },
    ]);
  };

  const STATUS_LABELS: Record<string, string> = {
    prescribed: 'Prescribed',
    sent_to_pharmacy: 'At Pharmacy',
    picked_up: 'Picked Up',
    active: 'Active',
    discontinued: 'Discontinued',
  };

  const buildMedList = () => {
    const medications = patient.medications || [];
    const allergies = patient.allergies || [];

    let text = `MY MEDICATIONS\n`;
    text += `Name: ${patient.name}\n`;
    text += `Date: ${new Date().toLocaleDateString()}\n\n`;

    if (allergies.length > 0) {
      text += `ALLERGIES: ${allergies.map((a) => a.name).join(', ')}\n\n`;
    }

    text += `MEDICATIONS:\n${'-'.repeat(40)}\n\n`;

    const active = medications.filter((m) => m.status !== 'discontinued');
    const discontinued = medications.filter((m) => m.status === 'discontinued');

    active.forEach((med, i) => {
      text += `${i + 1}. ${med.name} — ${med.dosage}, ${med.frequency}\n`;
      if (med.reason) text += `   For: ${med.reason}\n`;
      if (med.doctor) text += `   Doctor: Dr. ${med.doctor}\n`;
      if (med.status && med.status !== 'active') {
        text += `   Status: ${STATUS_LABELS[med.status] || med.status}\n`;
      }
      if (med.refillDate) {
        const daysUntil = Math.ceil(
          (new Date(med.refillDate).getTime() - Date.now()) / (1000 * 60 * 60 * 24)
        );
        text += `   Next Refill: ${new Date(med.refillDate).toLocaleDateString()}`;
        if (daysUntil < 0) text += ` (${Math.abs(daysUntil)} days overdue)`;
        else if (daysUntil <= 7) text += ` (in ${daysUntil} days)`;
        text += '\n';
      }
      text += '\n';
    });

    if (discontinued.length > 0) {
      text += `DISCONTINUED:\n`;
      discontinued.forEach((med) => {
        text += `  - ${med.name} ${med.dosage}\n`;
      });
      text += '\n';
    }

    text += `Keep this list with you. Show it to your doctor or pharmacist at every visit.\n`;
    text += `Generated by MedGuardian | ${new Date().toLocaleDateString()}\n`;
    return text;
  };

  const buildClinicalDoc = (notes?: string) => {
    const medications = patient.medications || [];
    const allergies = patient.allergies || [];

    let text = `MEDICATION RECONCILIATION\n`;
    text += `${'='.repeat(50)}\n`;
    text += `Patient: ${patient.name}\n`;
    text += `Date: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}\n`;
    text += `Total Medications: ${medications.length}\n\n`;

    text += `ALLERGIES:\n`;
    if (allergies.length > 0) {
      allergies.forEach((a) => (text += `  - ${a.name}\n`));
    } else {
      text += `  NKDA (No Known Drug Allergies)\n`;
    }
    if (allergyConflicts.length > 0) {
      text += `  ** ALLERGY CONFLICTS DETECTED:\n`;
      allergyConflicts.forEach((c) => {
        text += `     - ${c.medication} conflicts with allergy to ${c.allergy}\n`;
      });
    }
    text += '\n';

    const active = medications.filter((m) => m.status !== 'discontinued');
    const discontinued = medications.filter((m) => m.status === 'discontinued');
    const pendingPickup = medications.filter((m) => m.status === 'sent_to_pharmacy' || m.status === 'prescribed');

    if (pendingPickup.length > 0) {
      text += `PENDING PICKUP (${pendingPickup.length}):\n`;
      pendingPickup.forEach((med) => {
        text += `  - ${med.name} ${med.dosage} — ${STATUS_LABELS[med.status || 'prescribed']}\n`;
      });
      text += '\n';
    }

    text += `ACTIVE MEDICATIONS:\n`;
    active.forEach((med, i) => {
      let line = `  ${i + 1}. ${med.name} ${med.dosage} — ${med.frequency}`;
      if (med.doctor) line += ` (Dr. ${med.doctor})`;
      text += `${line}\n`;
      if (med.reason) text += `     Indication: ${med.reason}\n`;
      if (med.status && med.status !== 'active') {
        text += `     Status: ${STATUS_LABELS[med.status]}\n`;
      }
      if (med.refillDate) {
        const daysUntil = Math.ceil(
          (new Date(med.refillDate).getTime() - Date.now()) / (1000 * 60 * 60 * 24)
        );
        if (daysUntil < 0) {
          text += `     ** REFILL OVERDUE by ${Math.abs(daysUntil)} days\n`;
        } else if (daysUntil <= 7) {
          text += `     Refill due in ${daysUntil} days (${new Date(med.refillDate).toLocaleDateString()})\n`;
        }
      }
    });
    text += '\n';

    if (discontinued.length > 0) {
      text += `DISCONTINUED MEDICATIONS:\n`;
      discontinued.forEach((med) => {
        text += `  - ${med.name} ${med.dosage}`;
        if (med.statusUpdatedAt) text += ` (d/c ${new Date(med.statusUpdatedAt).toLocaleDateString()})`;
        text += '\n';
      });
      text += '\n';
    }

    text += `DRUG INTERACTIONS: ${interactions.length} identified\n`;
    if (interactions.length > 0) {
      const major = interactions.filter((ix) => ix.severity === 'major');
      const moderate = interactions.filter((ix) => ix.severity === 'moderate');
      if (major.length > 0) {
        major.forEach((ix) => {
          text += `  ** MAJOR: ${ix.med1} + ${ix.med2} — ${ix.description}\n`;
        });
      }
      if (moderate.length > 0) {
        moderate.forEach((ix) => {
          text += `  - Moderate: ${ix.med1} + ${ix.med2} — ${ix.description}\n`;
        });
      }
    } else {
      text += `  No significant interactions identified\n`;
    }
    text += '\n';

    text += `NOTES:\n`;
    text += notes?.trim() ? `  ${notes.trim()}\n` : `  (No notes)\n`;
    text += '\n';

    const visitNotes = patient.visitNotes || [];
    if (visitNotes.length > 0) {
      text += `ENCOUNTER HISTORY (${visitNotes.length}):\n`;
      visitNotes.slice(0, 10).forEach((note) => {
        const d = new Date(note.timestamp);
        const dateStr = d.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
        const timeStr = d.toLocaleTimeString('en-US', { hour: 'numeric', minute: '2-digit' });
        text += `  [${dateStr} ${timeStr}] ${note.text}\n`;
      });
      if (visitNotes.length > 10) text += `  ... and ${visitNotes.length - 10} earlier notes\n`;
      text += '\n';
    }

    text += `${'='.repeat(50)}\n`;
    text += `MedGuardian Medication Reconciliation\n`;
    text += `Generated: ${new Date().toLocaleString()}\n`;
    text += `This is a reference document — verify with clinical sources.\n`;
    return text;
  };

  const buildInteractionReport = () => {
    const medications = patient.medications || [];
    const allergies = patient.allergies || [];
    const activeMeds = medications.filter((m) => m.status !== 'discontinued');
    const major = interactions.filter((ix) => ix.severity === 'major');
    const moderate = interactions.filter((ix) => ix.severity === 'moderate');

    let text = `MEDICATION SAFETY REPORT\n`;
    text += `${'='.repeat(50)}\n`;
    text += `Patient: ${patient.name}\n`;
    text += `Date: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}\n`;
    text += `Active Medications: ${activeMeds.length}\n`;
    text += `Interactions Found: ${interactions.length} (${major.length} major, ${moderate.length} moderate)\n`;
    text += `Allergy Conflicts: ${allergyConflicts.length}\n`;
    text += `${'='.repeat(50)}\n\n`;

    // Summary at top for quick scan
    if (major.length > 0 || allergyConflicts.length > 0) {
      text += `*** ACTION REQUIRED ***\n`;
      if (allergyConflicts.length > 0) {
        allergyConflicts.forEach((c) => {
          text += `  ALLERGY: ${c.medication} — patient allergic to ${c.allergy}\n`;
        });
      }
      if (major.length > 0) {
        major.forEach((ix) => {
          text += `  MAJOR: ${ix.med1} + ${ix.med2} — ${ix.description}\n`;
        });
      }
      text += '\n';
    }

    text += `MEDICATIONS REVIEWED:\n`;
    activeMeds.forEach((med, i) => {
      text += `  ${i + 1}. ${med.name} ${med.dosage} (${med.frequency})`;
      if (med.status && med.status !== 'active') text += ` [${STATUS_LABELS[med.status]}]`;
      text += '\n';
    });
    text += '\n';

    if (allergies.length > 0) {
      text += `KNOWN ALLERGIES: ${allergies.map((a) => a.name).join(', ')}\n\n`;
    }

    if (interactions.length === 0) {
      text += `INTERACTION SCREENING RESULT:\n`;
      text += `  No significant drug-drug interactions identified.\n\n`;
    } else {
      if (major.length > 0) {
        text += `MAJOR INTERACTIONS (${major.length}):\n`;
        text += `${'-'.repeat(40)}\n`;
        major.forEach((ix) => {
          text += `  ${ix.med1} + ${ix.med2}\n`;
          text += `  ${ix.description}\n`;
          if (ix.info) text += `  Clinical Note: ${ix.info}\n`;
          text += '\n';
        });
      }
      if (moderate.length > 0) {
        text += `MODERATE INTERACTIONS (${moderate.length}):\n`;
        text += `${'-'.repeat(40)}\n`;
        moderate.forEach((ix) => {
          text += `  ${ix.med1} + ${ix.med2}\n`;
          text += `  ${ix.description}\n`;
          if (ix.info) text += `  Clinical Note: ${ix.info}\n`;
          text += '\n';
        });
      }
    }

    text += `${'='.repeat(50)}\n`;
    text += `MedGuardian Safety Report | ${new Date().toLocaleString()}\n`;
    text += `Always verify with clinical references before making changes.\n`;
    return text;
  };

  const shareText = async (text: string, fileName: string) => {
    try {
      if (Platform.OS === 'web') {
        await Share.share({ message: text });
      } else {
        const file = new File(Paths.cache, fileName);
        file.write(text);
        if (await Sharing.isAvailableAsync()) {
          await Sharing.shareAsync(file.uri, { mimeType: 'text/plain' });
        } else {
          await Share.share({ message: text });
        }
      }
    } catch {
      await Share.share({ message: text });
    }
  };

  // Share modal
  const [showShareModal, setShowShareModal] = useState(false);
  const [shareMode, setShareMode] = useState<'patient' | 'clinical' | 'interactions'>('clinical');

  const handleShareMenu = () => {
    const medications = patient.medications || [];
    if (medications.length === 0) {
      Alert.alert('No Medications', 'No medications to share.');
      return;
    }
    setShareMode('clinical');
    setShowShareModal(true);
  };

  const handleShareAction = async (action: 'share' | 'copy') => {
    const dateSuffix = new Date().toISOString().split('T')[0];
    const safeName = patient.name.replace(/\s/g, '-');
    const text = shareMode === 'clinical'
      ? buildClinicalDoc(patient.notes)
      : shareMode === 'interactions'
      ? buildInteractionReport()
      : buildMedList();
    const fileName = shareMode === 'clinical'
      ? `med-rec-${safeName}-${dateSuffix}.txt`
      : shareMode === 'interactions'
      ? `safety-report-${safeName}-${dateSuffix}.txt`
      : `my-meds-${safeName}-${dateSuffix}.txt`;

    const labels = {
      clinical: 'Medication reconciliation',
      interactions: 'Safety report',
      patient: 'Patient medication list',
    };

    setShowShareModal(false);

    if (action === 'copy') {
      await Clipboard.setStringAsync(text);
      Alert.alert('Copied', `${labels[shareMode]} copied to clipboard.`);
    } else {
      await shareText(text, fileName);
    }
  };

  // Interaction checker
  const [showInteractionCheck, setShowInteractionCheck] = useState(false);
  const [checkDrugName, setCheckDrugName] = useState('');
  const [checkResults, setCheckResults] = useState<Interaction[] | null>(null);
  const [checkLoading, setCheckLoading] = useState(false);

  const handleInteractionCheck = async () => {
    const drugName = checkDrugName.trim();
    if (!drugName) return;
    if (patient.medications.length === 0) {
      Alert.alert('No Medications', 'Add medications first to check for interactions.');
      return;
    }

    setCheckLoading(true);
    try {
      // Create a temporary medication to check against the current list
      const tempMed: Medication = {
        id: -1,
        name: drugName,
        dosage: '',
        frequency: '',
        doctor: '',
        reason: '',
        refillDate: null,
        addedDate: new Date().toISOString(),
        schedule: 'morning',
      };
      const allMeds = [...patient.medications, tempMed];
      const results = await checkInteractions(allMeds);
      // Filter to only interactions involving the checked drug
      const relevant = results.filter(
        (r) => r.med1.toLowerCase() === drugName.toLowerCase() || r.med2.toLowerCase() === drugName.toLowerCase()
      );
      setCheckResults(relevant);
    } catch {
      setCheckResults([]);
    } finally {
      setCheckLoading(false);
    }
  };

  // Patient rename on long-press
  const handleRenamePatient = (id: string, currentName: string) => {
    Alert.prompt
      ? Alert.prompt('Rename Patient', '', (newName) => {
          if (newName?.trim()) renamePatient(id, newName.trim());
        }, 'plain-text', currentName)
      : Alert.alert('Rename Patient', `Current name: ${currentName}`, [
          { text: 'Cancel', style: 'cancel' },
          {
            text: 'Rename',
            onPress: () => {
              setRenamingPatientId(id);
              setRenamingPatientText(currentName);
            },
          },
        ]);
  };
  const [renamingPatientId, setRenamingPatientId] = useState<string | null>(null);
  const [renamingPatientText, setRenamingPatientText] = useState('');


  // Patient selector with inline add
  const [newPatientName, setNewPatientName] = useState('');
  const [showNewPatient, setShowNewPatient] = useState(false);
  const [showPatientModal, setShowPatientModal] = useState(false);
  const patientCount = Object.keys(patients).length;

  // Drag-to-reorder state
  const [draggingId, setDraggingId] = useState<string | null>(null);
  const [dragOrder, setDragOrder] = useState<string[] | null>(null);
  const dragX = useRef(new Animated.Value(0)).current;
  const chipLayouts = useRef<Record<string, { x: number; width: number }>>({});
  const longPressTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const isDragging = useRef(false);

  const handleChipLayout = useCallback((id: string, e: LayoutChangeEvent) => {
    const { x, width } = e.nativeEvent.layout;
    chipLayouts.current[id] = { x, width };
  }, []);

  const panResponder = useRef(
    PanResponder.create({
      onStartShouldSetPanResponder: () => false,
      onMoveShouldSetPanResponder: (_, gs) => {
        // Only capture if we're in drag mode (long hold triggered) and moved enough
        return isDragging.current && Math.abs(gs.dx) > 5;
      },
      onPanResponderGrant: () => {},
      onPanResponderMove: (_, gs) => {
        if (!isDragging.current) return;
        dragX.setValue(gs.dx);

        // Calculate reorder based on position
        const currentIds = dragOrder ?? Object.keys(patients);
        const dragIdx = draggingId ? currentIds.indexOf(draggingId) : -1;
        if (dragIdx < 0 || !draggingId) return;

        const dragLayout = chipLayouts.current[draggingId];
        if (!dragLayout) return;
        const currentCenter = dragLayout.x + dragLayout.width / 2 + gs.dx;

        // Check if we've crossed into a neighbor's territory
        for (let i = 0; i < currentIds.length; i++) {
          if (i === dragIdx) continue;
          const layout = chipLayouts.current[currentIds[i]];
          if (!layout) continue;
          const center = layout.x + layout.width / 2;

          if (i < dragIdx && currentCenter < center) {
            const newOrder = [...currentIds];
            newOrder.splice(dragIdx, 1);
            newOrder.splice(i, 0, draggingId);
            setDragOrder(newOrder);
            break;
          } else if (i > dragIdx && currentCenter > center) {
            const newOrder = [...currentIds];
            newOrder.splice(dragIdx, 1);
            newOrder.splice(i, 0, draggingId);
            setDragOrder(newOrder);
            break;
          }
        }
      },
      onPanResponderRelease: () => {
        if (isDragging.current && dragOrder) {
          reorderPatients(dragOrder);
        }
        isDragging.current = false;
        setDraggingId(null);
        setDragOrder(null);
        dragX.setValue(0);
        if (longPressTimer.current) {
          clearTimeout(longPressTimer.current);
          longPressTimer.current = null;
        }
      },
      onPanResponderTerminate: () => {
        isDragging.current = false;
        setDraggingId(null);
        setDragOrder(null);
        dragX.setValue(0);
        if (longPressTimer.current) {
          clearTimeout(longPressTimer.current);
          longPressTimer.current = null;
        }
      },
    })
  ).current;

  const startDragTimer = useCallback((id: string) => {
    if (longPressTimer.current) clearTimeout(longPressTimer.current);
    // Long hold (800ms) starts drag mode — shorter hold (500ms) will trigger rename via onLongPress
    longPressTimer.current = setTimeout(() => {
      isDragging.current = true;
      setDraggingId(id);
      setDragOrder(Object.keys(patients));
      dragX.setValue(0);
    }, 800);
  }, [patients]);

  const cancelDragTimer = useCallback(() => {
    if (longPressTimer.current) {
      clearTimeout(longPressTimer.current);
      longPressTimer.current = null;
    }
  }, []);

  return (
    <View style={{ flex: 1 }}>
    <KeyboardAvoidingView style={{ flex: 1 }} behavior={Platform.OS === 'ios' ? 'padding' : undefined} keyboardVerticalOffset={90}>
    <ScrollView style={styles.container} contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled">
      {/* Patient Selector */}
      {patientCount > 5 ? (
        <View style={styles.patientSection}>
          <TouchableOpacity style={styles.patientDropdownBtn} onPress={() => setShowPatientModal(true)}>
            <Text style={styles.patientDropdownText}>{patient.name}</Text>
            <Text style={styles.patientDropdownMeta}>
              {patientCount} patients
            </Text>
          </TouchableOpacity>
          <PatientSelectorModal
            visible={showPatientModal}
            onClose={() => setShowPatientModal(false)}
            patients={patients}
            currentPatient={currentPatient}
            onSelectPatient={(id) => { setCurrentPatient(id); setShowPatientModal(false); }}
            onAddPatient={(name) => { addPatient(name); setShowPatientModal(false); }}
            onRenamePatient={renamePatient}
          />
        </View>
      ) : (
        <View style={styles.patientSection}>
          <ScrollView
            horizontal
            showsHorizontalScrollIndicator={false}
            style={styles.patientScroll}
            scrollEnabled={!draggingId}
          >
            <View style={styles.chipRow} {...panResponder.panHandlers}>
              {(dragOrder ?? Object.keys(patients)).map((id) => {
                const p = patients[id];
                if (!p) return null;
                const isBeingDragged = draggingId === id;
                return (
                  <Animated.View
                    key={id}
                    onLayout={(e) => handleChipLayout(id, e)}
                    style={[
                      isBeingDragged && {
                        transform: [{ translateX: dragX }],
                        zIndex: 10,
                        opacity: 0.85,
                        elevation: 4,
                        shadowColor: '#000',
                        shadowOffset: { width: 0, height: 2 },
                        shadowOpacity: 0.25,
                        shadowRadius: 4,
                      },
                      draggingId && !isBeingDragged && { opacity: 0.5 },
                    ]}
                  >
                    <TouchableOpacity
                      style={[
                        styles.patientChip,
                        id === currentPatient && styles.patientChipActive,
                        isBeingDragged && styles.patientChipDragging,
                      ]}
                      onPress={() => { if (!draggingId) setCurrentPatient(id); }}
                      onLongPress={() => { if (!isDragging.current) handleRenamePatient(id, p.name); }}
                      delayLongPress={500}
                      onPressIn={() => startDragTimer(id)}
                      onPressOut={() => { if (!isDragging.current) cancelDragTimer(); }}
                      activeOpacity={0.7}
                    >
                      <Text style={[styles.patientChipText, id === currentPatient && styles.patientChipTextActive]}>
                        {p.name}
                      </Text>
                      {isBeingDragged && (
                        <Text style={styles.dragHint}>&#x2630;</Text>
                      )}
                    </TouchableOpacity>
                  </Animated.View>
                );
              })}
              <TouchableOpacity style={styles.addPatientChip} onPress={() => setShowNewPatient(true)}>
                <Text style={styles.addPatientText}>+ Add</Text>
              </TouchableOpacity>
            </View>
          </ScrollView>

          {/* Inline rename input (Android fallback — no Alert.prompt) */}
          {renamingPatientId && (
            <View style={styles.newPatientRow}>
              <TextInput
                style={styles.newPatientInput}
                placeholder="New name..."
                value={renamingPatientText}
                onChangeText={setRenamingPatientText}
                autoFocus
                onSubmitEditing={() => {
                  if (renamingPatientText.trim()) renamePatient(renamingPatientId, renamingPatientText.trim());
                  setRenamingPatientId(null);
                }}
              />
              <TouchableOpacity
                style={styles.newPatientSave}
                onPress={() => {
                  if (renamingPatientText.trim()) renamePatient(renamingPatientId, renamingPatientText.trim());
                  setRenamingPatientId(null);
                }}
              >
                <Text style={styles.newPatientSaveText}>Save</Text>
              </TouchableOpacity>
              <TouchableOpacity onPress={() => setRenamingPatientId(null)}>
                <Text style={{ color: '#a0aec0', fontSize: 16, marginLeft: 10 }}>Cancel</Text>
              </TouchableOpacity>
            </View>
          )}

          {showNewPatient && (
            <View style={styles.newPatientRow}>
              <TextInput
                style={styles.newPatientInput}
                placeholder="Patient name..."
                value={newPatientName}
                onChangeText={setNewPatientName}
                autoFocus
              />
              <TouchableOpacity
                style={styles.newPatientSave}
                onPress={() => {
                  if (newPatientName.trim()) {
                    addPatient(newPatientName.trim());
                    setNewPatientName('');
                    setShowNewPatient(false);
                  }
                }}
              >
                <Text style={styles.newPatientSaveText}>Add</Text>
              </TouchableOpacity>
              <TouchableOpacity onPress={() => { setShowNewPatient(false); setNewPatientName(''); }}>
                <Text style={{ color: '#a0aec0', fontSize: 16, marginLeft: 10 }}>Cancel</Text>
              </TouchableOpacity>
            </View>
          )}
        </View>
      )}

      {/* Allergies */}
      <View style={styles.allergySection}>
        <View style={styles.allergyHeader}>
          <Text style={styles.allergyTitle}>Allergies</Text>
          <TouchableOpacity style={styles.addAllergyBtn} onPress={() => setShowAllergyInput(true)}>
            <Text style={styles.addAllergyText}>+ Add Allergy</Text>
          </TouchableOpacity>
        </View>

        {showAllergyInput && (
          <AutocompleteInput
            value={allergyText}
            onChangeText={setAllergyText}
            onSubmit={handleAddAllergy}
            placeholder="Type an allergy..."
            localSuggestions={COMMON_ALLERGENS}
            fetchSuggestions={fetchAllergySuggestions}
            accentColor="#fc8181"
            autoFocus
          />
        )}

        {(patient.allergies || []).length === 0 ? (
          <Text style={styles.emptyAllergy}>No allergies recorded</Text>
        ) : (
          patient.allergies.map((allergy) => (
            <View key={allergy.id} style={styles.allergyItem}>
              <Text style={styles.allergyName}>{allergy.name}</Text>
              <TouchableOpacity onPress={() => handleDeleteAllergy(allergy.id)}>
                <Text style={styles.allergyDelete}>x</Text>
              </TouchableOpacity>
            </View>
          ))
        )}
      </View>

      {/* Notes — combined encounter notes + pinned note */}
      <View style={styles.visitNotesSection}>
        <TouchableOpacity
          style={styles.visitNotesHeader}
          onPress={() => setShowVisitNotes(!showVisitNotes)}
          activeOpacity={0.7}
        >
          <View>
            <Text style={styles.visitNotesTitle}>Notes</Text>
            {(patient.visitNotes || []).length > 0 && (
              <Text style={styles.visitNotesCount}>
                {(patient.visitNotes || []).length} encounter{(patient.visitNotes || []).length !== 1 ? 's' : ''}
              </Text>
            )}
          </View>
          <Text style={styles.notesToggle}>{showVisitNotes ? '−' : '+'}</Text>
        </TouchableOpacity>

        {!showVisitNotes && (patient.visitNotes || []).length > 0 && (
          <Text style={styles.notesPreview} numberOfLines={2}>
            Latest: {(patient.visitNotes || [])[0]?.text}
          </Text>
        )}

        {showVisitNotes && (
          <View style={styles.visitNotesBody}>
            {/* Add new encounter note */}
            {!showVisitInput ? (
              <TouchableOpacity
                style={styles.addVisitNoteBtn}
                onPress={() => setShowVisitInput(true)}
              >
                <Text style={styles.addVisitNoteBtnText}>+ New Encounter Note</Text>
              </TouchableOpacity>
            ) : (
              <View style={styles.visitNoteInputArea}>
                <TextInput
                  style={styles.visitNoteInput}
                  placeholder="Encounter notes — vitals, observations, plan changes..."
                  value={newVisitNote}
                  onChangeText={setNewVisitNote}
                  multiline
                  textAlignVertical="top"
                  autoFocus
                />
                <View style={styles.visitNoteInputActions}>
                  <TouchableOpacity
                    style={[styles.visitNoteSaveBtn, !newVisitNote.trim() && { opacity: 0.5 }]}
                    onPress={handleAddVisitNote}
                    disabled={!newVisitNote.trim()}
                  >
                    <Text style={styles.visitNoteSaveText}>Save Note</Text>
                  </TouchableOpacity>
                  <TouchableOpacity
                    onPress={() => { setShowVisitInput(false); setNewVisitNote(''); }}
                  >
                    <Text style={styles.visitNoteCancelText}>Cancel</Text>
                  </TouchableOpacity>
                </View>
              </View>
            )}

            {/* Encounter note entries */}
            {(patient.visitNotes || []).length === 0 ? (
              <Text style={styles.visitNotesEmpty}>No encounter notes yet</Text>
            ) : (
              (patient.visitNotes || []).map((note) => (
                <View key={note.id} style={styles.visitNoteCard}>
                  <View style={styles.visitNoteCardHeader}>
                    <Text style={styles.visitNoteTimestamp}>
                      {formatVisitDate(note.timestamp)}
                    </Text>
                    <TouchableOpacity
                      onPress={() => handleDeleteVisitNote(note.id)}
                      hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
                    >
                      <Text style={styles.visitNoteDelete}>x</Text>
                    </TouchableOpacity>
                  </View>
                  <Text style={styles.visitNoteText}>{note.text}</Text>
                </View>
              ))
            )}

            {/* Pinned/general note (the old free-text scratchpad) */}
            <TouchableOpacity
              style={styles.pinnedNoteToggle}
              onPress={() => setShowNotes(!showNotes)}
            >
              <Text style={styles.pinnedNoteToggleText}>
                {showNotes ? '− Hide' : '+'} Pinned Note {patient.notes?.trim() ? '' : '(empty)'}
              </Text>
            </TouchableOpacity>
            {showNotes && (
              <TextInput
                style={styles.notesInput}
                placeholder="Persistent note — standing orders, background info..."
                value={patient.notes || ''}
                onChangeText={updatePatientNotes}
                multiline
                textAlignVertical="top"
              />
            )}
            {!showNotes && patient.notes?.trim() ? (
              <Text style={styles.notesPreview} numberOfLines={2}>{patient.notes.trim()}</Text>
            ) : null}
          </View>
        )}
      </View>

      {/* Stats */}
      <StatsBar />

      {/* Alerts */}
      <AlertsList />

      {/* Schedule */}
      <ScheduleView
        medications={patient.medications}
        onPressMedication={(med) => navigation.navigate('MedicationDetail', { medication: med })}
      />

      {/* Add Medication Button */}
      <TouchableOpacity
        style={styles.addMedBtn}
        onPress={() => navigation.navigate('AddMedication')}
        activeOpacity={0.8}
      >
        <Text style={styles.addMedBtnIcon}>+</Text>
        <Text style={styles.addMedBtnText}>Add Medication</Text>
      </TouchableOpacity>

      {/* Ask MedGuardian Button */}
      <TouchableOpacity
        style={styles.askBtn}
        onPress={() => navigation.navigate('Ask')}
        activeOpacity={0.8}
      >
        <Text style={styles.askBtnIcon}>?</Text>
        <Text style={styles.askBtnText}>Ask MedGuardian</Text>
      </TouchableOpacity>

      {/* Interaction Checker */}
      {patient.medications.length > 0 && (
        <View style={styles.interactionCheckSection}>
          <TouchableOpacity
            style={styles.interactionCheckToggle}
            onPress={() => {
              setShowInteractionCheck(!showInteractionCheck);
              setCheckResults(null);
              setCheckDrugName('');
            }}
          >
            <Text style={styles.interactionCheckToggleText}>
              {showInteractionCheck ? '- Hide' : '+ Check'} Drug Interactions
            </Text>
          </TouchableOpacity>

          {showInteractionCheck && (
            <View style={styles.interactionCheckBody}>
              <Text style={styles.interactionCheckHint}>
                Type a drug name to check for interactions with current medications
              </Text>
              <View style={{ zIndex: 10 }}>
                <AutocompleteInput
                  value={checkDrugName}
                  onChangeText={(text) => { setCheckDrugName(text); setCheckResults(null); }}
                  placeholder="e.g., Warfarin, Ibuprofen..."
                  fetchSuggestions={fetchDrugSuggestions}
                  accentColor="#e2e8f0"
                  showSubmitButton={false}
                  inputStyle={styles.interactionCheckInput}
                />
              </View>
              <TouchableOpacity
                style={[styles.interactionCheckBtn, !checkDrugName.trim() && { opacity: 0.5 }]}
                onPress={handleInteractionCheck}
                disabled={!checkDrugName.trim() || checkLoading}
              >
                {checkLoading ? (
                  <ActivityIndicator size="small" color="#fff" />
                ) : (
                  <Text style={styles.interactionCheckBtnText}>Check Interactions</Text>
                )}
              </TouchableOpacity>

              {checkResults !== null && (
                <View style={styles.interactionCheckResults}>
                  {checkResults.length === 0 ? (
                    <View style={styles.interactionCheckSafe}>
                      <Text style={styles.interactionCheckSafeText}>
                        No interactions found between {checkDrugName} and current medications.
                      </Text>
                    </View>
                  ) : (
                    checkResults.map((ix, i) => (
                      <View
                        key={i}
                        style={[
                          styles.interactionCheckItem,
                          ix.severity === 'major' && styles.interactionCheckMajor,
                        ]}
                      >
                        <Text style={styles.interactionCheckSeverity}>
                          {ix.severity.toUpperCase()}
                        </Text>
                        <Text style={styles.interactionCheckPair}>
                          {ix.med1} + {ix.med2}
                        </Text>
                        <Text style={styles.interactionCheckDesc}>{ix.description}</Text>
                        {ix.info ? (
                          <Text style={styles.interactionCheckInfo}>{ix.info}</Text>
                        ) : null}
                      </View>
                    ))
                  )}
                  <View style={styles.verifyPrompt}>
                    <Text style={styles.verifyPromptText}>
                      Always verify interactions with your pharmacist or at drugs.com/interaction-checker. This is not a complete database.
                    </Text>
                  </View>
                </View>
              )}
            </View>
          )}
        </View>
      )}

      {/* Medications List */}
      <View style={styles.medsHeader}>
        <Text style={styles.medsTitle}>Current Medications</Text>
        {patient.medications.length > 0 && (
          <TouchableOpacity style={styles.shareBtn} onPress={handleShareMenu}>
            <Text style={styles.shareBtnText}>Export / Share</Text>
          </TouchableOpacity>
        )}
      </View>

      {patient.medications.length === 0 ? (
        <View style={styles.emptyState}>
          <Text style={styles.emptyText}>No medications added yet</Text>
          <Text style={styles.emptySubText}>
            Tap "Add Medication" above to get started
          </Text>
        </View>
      ) : (
        patient.medications.map((med) => (
          <MedicationCard
            key={med.id}
            medication={med}
            interactions={interactions}
            allergyConflicts={allergyConflicts}
            onDelete={deleteMedication}
            onPress={() => navigation.navigate('MedicationDetail', { medication: med })}
          />
        ))
      )}

      <Text style={styles.footer}>* This app displays general medication information from public databases. Not medical advice. Consult your healthcare provider.</Text>

      <View style={{ height: 40 }} />
    </ScrollView>
    </KeyboardAvoidingView>

    {/* Share Modal */}
    <Modal visible={showShareModal} animationType="slide" transparent>
      <KeyboardAvoidingView
        style={styles.shareOverlay}
        behavior={Platform.OS === 'ios' ? 'padding' : undefined}
      >
        <TouchableOpacity
          style={styles.shareBackdrop}
          activeOpacity={1}
          onPress={() => setShowShareModal(false)}
        />
        <View style={styles.shareSheet}>
          <View style={styles.shareHandle} />
          <Text style={styles.shareTitle}>Export Patient Report</Text>

          {/* Format toggle */}
          <View style={styles.shareModeRow}>
            <TouchableOpacity
              style={[styles.shareModeBtn, shareMode === 'clinical' && styles.shareModeBtnActive]}
              onPress={() => setShareMode('clinical')}
            >
              <Text style={[styles.shareModeText, shareMode === 'clinical' && styles.shareModeTextActive]}>
                Med Rec
              </Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={[styles.shareModeBtn, shareMode === 'interactions' && styles.shareModeBtnActive]}
              onPress={() => setShareMode('interactions')}
            >
              <Text style={[styles.shareModeText, shareMode === 'interactions' && styles.shareModeTextActive]}>
                Safety Check
              </Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={[styles.shareModeBtn, shareMode === 'patient' && styles.shareModeBtnActive]}
              onPress={() => setShareMode('patient')}
            >
              <Text style={[styles.shareModeText, shareMode === 'patient' && styles.shareModeTextActive]}>
                Patient Copy
              </Text>
            </TouchableOpacity>
          </View>
          <Text style={styles.shareModeDesc}>
            {shareMode === 'clinical'
              ? `Medication reconciliation with status, interactions, allergies & encounter notes — for provider handoff or chart documentation`
              : shareMode === 'interactions'
              ? `Drug interaction & allergy safety report — ${interactions.length} interaction${interactions.length !== 1 ? 's' : ''}, ${allergyConflicts.length} allergy conflict${allergyConflicts.length !== 1 ? 's' : ''}`
              : 'Clean medication list with dosages & refill dates — for the patient or caregiver to take home'}
          </Text>

          {/* Action buttons */}
          <View style={styles.shareActions}>
            <TouchableOpacity
              style={styles.shareActionBtn}
              onPress={() => handleShareAction('share')}
            >
              <Text style={styles.shareActionText}>Share File</Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={styles.shareCopyBtn}
              onPress={() => handleShareAction('copy')}
            >
              <Text style={styles.shareCopyText}>Copy to Clipboard</Text>
            </TouchableOpacity>
          </View>

          <TouchableOpacity
            style={styles.shareCancelBtn}
            onPress={() => setShowShareModal(false)}
          >
            <Text style={styles.shareCancelText}>Cancel</Text>
          </TouchableOpacity>
        </View>
      </KeyboardAvoidingView>
    </Modal>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f7fa' },
  content: { padding: 16 },
  footer: { fontSize: 11, color: '#a0aec0', textAlign: 'center', marginTop: 20, paddingHorizontal: 10 },
  patientSection: { marginBottom: 16 },
  patientScroll: { flexDirection: 'row' },
  chipRow: { flexDirection: 'row', alignItems: 'center' },
  patientChip: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: '#e2e8f0',
    marginRight: 8,
  },
  patientChipActive: { backgroundColor: '#667eea' },
  patientChipDragging: {
    borderWidth: 2,
    borderColor: '#4c63d2',
    borderStyle: 'dashed',
  },
  patientChipText: { fontSize: 14, color: '#4a5568' },
  patientChipTextActive: { color: '#fff', fontWeight: '600' },
  dragHint: { fontSize: 12, color: 'rgba(255,255,255,0.7)', marginLeft: 4 },
  addPatientChip: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#cbd5e0',
    borderStyle: 'dashed',
  },
  addPatientText: { fontSize: 14, color: '#667eea' },
  newPatientRow: { flexDirection: 'row', alignItems: 'center', marginTop: 10 },
  newPatientInput: {
    flex: 1,
    borderWidth: 2,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    padding: 10,
    fontSize: 14,
    backgroundColor: '#fff',
    color: '#2d3748',
  },
  newPatientSave: {
    backgroundColor: '#667eea',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginLeft: 8,
  },
  newPatientSaveText: { color: '#fff', fontWeight: '600' },
  allergySection: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  allergyHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  allergyTitle: { fontWeight: '600', fontSize: 14, color: '#4a5568' },
  addAllergyBtn: { backgroundColor: '#fc8181', paddingVertical: 6, paddingHorizontal: 12, borderRadius: 6 },
  addAllergyText: { color: '#fff', fontSize: 12, fontWeight: '600' },
  allergyInputRow: { flexDirection: 'row', marginBottom: 10 },
  allergyInput: {
    flex: 1,
    borderWidth: 2,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    padding: 10,
    fontSize: 14,
    color: '#2d3748',
  },
  allergyInputSave: {
    backgroundColor: '#fc8181',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginLeft: 8,
    justifyContent: 'center',
  },
  emptyAllergy: { color: '#a0aec0', fontStyle: 'italic', fontSize: 13 },
  allergyItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 8,
    backgroundColor: '#fff5f5',
    borderWidth: 1,
    borderColor: '#fc8181',
    borderRadius: 6,
    marginBottom: 6,
  },
  allergyName: { color: '#c53030', fontWeight: '600', fontSize: 14 },
  allergyDelete: { color: '#fc8181', fontSize: 18, paddingHorizontal: 8 },
  medsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  medsTitle: { fontSize: 18, fontWeight: '700', color: '#2d3748' },
  shareBtn: { backgroundColor: '#48bb78', paddingVertical: 8, paddingHorizontal: 16, borderRadius: 8 },
  shareBtnText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  emptyState: { alignItems: 'center', padding: 40 },
  emptyText: { fontSize: 16, color: '#a0aec0', marginBottom: 8 },
  emptySubText: { fontSize: 14, color: '#cbd5e0', textAlign: 'center' },
  addMedBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#667eea',
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
    gap: 8,
    elevation: 2,
    shadowColor: '#667eea',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  addMedBtnIcon: { color: '#fff', fontSize: 22, fontWeight: '700' },
  addMedBtnText: { color: '#fff', fontSize: 17, fontWeight: '700' },
  askBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#38b2ac',
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
    gap: 8,
    elevation: 2,
    shadowColor: '#38b2ac',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  askBtnIcon: { color: '#fff', fontSize: 22, fontWeight: '700' },
  askBtnText: { color: '#fff', fontSize: 17, fontWeight: '700' },
  patientDropdownBtn: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#667eea',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 10,
  },
  patientDropdownText: { color: '#fff', fontSize: 16, fontWeight: '600' },
  patientDropdownMeta: { color: 'rgba(255,255,255,0.7)', fontSize: 13 },
  interactionCheckSection: {
    marginBottom: 20,
  },
  interactionCheckToggle: {
    backgroundColor: '#fff',
    borderWidth: 2,
    borderColor: '#667eea',
    borderRadius: 10,
    padding: 12,
    alignItems: 'center',
  },
  interactionCheckToggleText: { color: '#667eea', fontSize: 15, fontWeight: '600' },
  interactionCheckBody: {
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    padding: 14,
    marginTop: 8,
  },
  interactionCheckHint: { fontSize: 13, color: '#718096', marginBottom: 10 },
  interactionCheckInput: {
    borderWidth: 2,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    backgroundColor: '#fff',
    color: '#2d3748',
  },
  interactionCheckBtn: {
    backgroundColor: '#667eea',
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 10,
  },
  interactionCheckBtnText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  interactionCheckResults: { marginTop: 12 },
  interactionCheckSafe: {
    backgroundColor: '#f0fff4',
    borderWidth: 1,
    borderColor: '#48bb78',
    borderRadius: 8,
    padding: 14,
  },
  interactionCheckSafeText: { color: '#276749', fontSize: 14 },
  interactionCheckItem: {
    backgroundColor: '#fffaf0',
    borderWidth: 1,
    borderColor: '#ed8936',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
  },
  interactionCheckMajor: {
    backgroundColor: '#fff5f5',
    borderColor: '#e53e3e',
  },
  interactionCheckSeverity: {
    fontSize: 11,
    fontWeight: '700',
    color: '#c53030',
    textTransform: 'uppercase',
    marginBottom: 4,
  },
  interactionCheckPair: { fontSize: 14, fontWeight: '600', color: '#2d3748', marginBottom: 4 },
  interactionCheckDesc: { fontSize: 13, color: '#4a5568', marginBottom: 4 },
  interactionCheckInfo: { fontSize: 12, color: '#718096', fontStyle: 'italic' },
  verifyPrompt: {
    backgroundColor: '#ebf8ff',
    borderWidth: 1,
    borderColor: '#90cdf4',
    borderRadius: 8,
    padding: 12,
    marginTop: 8,
  },
  verifyPromptText: { fontSize: 12, color: '#2b6cb0', lineHeight: 18 },

  // Share modal
  shareOverlay: { flex: 1, justifyContent: 'flex-end' },
  shareBackdrop: { flex: 1 },
  shareSheet: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingHorizontal: 20,
    paddingBottom: 30,
  },
  shareHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#e2e8f0',
    borderRadius: 2,
    alignSelf: 'center',
    marginTop: 12,
    marginBottom: 16,
  },
  shareTitle: { fontSize: 18, fontWeight: '700', color: '#2d3748', marginBottom: 14 },
  shareModeRow: { flexDirection: 'row', gap: 8, marginBottom: 10 },
  shareModeBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: '#e2e8f0',
    alignItems: 'center',
  },
  shareModeBtnActive: { borderColor: '#667eea', backgroundColor: '#667eea' },
  shareModeText: { fontSize: 14, fontWeight: '600', color: '#4a5568' },
  shareModeTextActive: { color: '#fff' },
  shareModeDesc: { fontSize: 12, color: '#a0aec0', marginBottom: 14 },

  // Notes (shared styles for visit notes + pinned note)
  notesToggle: { fontSize: 18, color: '#667eea', fontWeight: '700' },
  notesInput: {
    borderWidth: 2,
    borderColor: '#e2e8f0',
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    minHeight: 80,
    backgroundColor: '#f7fafc',
    marginTop: 6,
    color: '#2d3748',
  },
  notesPreview: {
    fontSize: 13,
    color: '#718096',
    marginTop: 6,
  },
  pinnedNoteToggle: {
    paddingVertical: 10,
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: '#e2e8f0',
  },
  pinnedNoteToggleText: {
    fontSize: 13,
    color: '#667eea',
    fontWeight: '600',
  },
  shareActions: { flexDirection: 'row', gap: 10, marginBottom: 10 },
  shareActionBtn: {
    flex: 1,
    backgroundColor: '#667eea',
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
  },
  shareActionText: { color: '#fff', fontSize: 15, fontWeight: '700' },
  shareCopyBtn: {
    flex: 1,
    borderWidth: 2,
    borderColor: '#667eea',
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
  },
  shareCopyText: { color: '#667eea', fontSize: 15, fontWeight: '600' },
  shareCancelBtn: { padding: 12, alignItems: 'center' },
  shareCancelText: { color: '#a0aec0', fontSize: 14, fontWeight: '600' },

  // Visit notes (encounter-based)
  visitNotesSection: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  visitNotesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  visitNotesTitle: { fontWeight: '600', fontSize: 14, color: '#4a5568' },
  visitNotesCount: { fontSize: 12, color: '#a0aec0', marginTop: 2 },
  visitNotesBody: { marginTop: 12 },
  addVisitNoteBtn: {
    backgroundColor: '#667eea',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 12,
  },
  addVisitNoteBtnText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  visitNoteInputArea: { marginBottom: 12 },
  visitNoteInput: {
    borderWidth: 2,
    borderColor: '#667eea',
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    minHeight: 80,
    backgroundColor: '#f7fafc',
    color: '#2d3748',
  },
  visitNoteInputActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    marginTop: 8,
  },
  visitNoteSaveBtn: {
    backgroundColor: '#667eea',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  visitNoteSaveText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  visitNoteCancelText: { color: '#a0aec0', fontSize: 14 },
  visitNotesEmpty: { color: '#a0aec0', fontStyle: 'italic', fontSize: 13 },
  visitNoteCard: {
    backgroundColor: '#f7fafc',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e2e8f0',
    padding: 12,
    marginBottom: 8,
  },
  visitNoteCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  visitNoteTimestamp: {
    fontSize: 12,
    fontWeight: '600',
    color: '#667eea',
  },
  visitNoteDelete: {
    color: '#e53e3e',
    fontSize: 16,
    fontWeight: '600',
    paddingHorizontal: 6,
  },
  visitNoteText: {
    fontSize: 14,
    color: '#2d3748',
    lineHeight: 20,
  },
});
