import React, { useState } from 'react';
import {
  View,
  Text,
  ScrollView,
  TouchableOpacity,
  StyleSheet,
  Alert,
  TextInput,
  Share,
  Platform,
} from 'react-native';
import { File, Paths } from 'expo-file-system';
import * as Sharing from 'expo-sharing';
import { useApp } from '../context/AppContext';
import StatsBar from '../components/StatsBar';
import AlertsList from '../components/AlertsList';
import ScheduleView from '../components/ScheduleView';
import MedicationCard from '../components/MedicationCard';

export default function HomeScreen({ navigation }: any) {
  const {
    patients,
    currentPatient,
    currentUserType,
    setCurrentUserType,
    setCurrentPatient,
    addPatient,
    deleteMedication,
    addAllergy,
    deleteAllergy,
    getCurrentPatient,
    interactions,
    allergyConflicts,
  } = useApp();

  const patient = getCurrentPatient();
  const [showAllergyInput, setShowAllergyInput] = useState(false);
  const [allergyText, setAllergyText] = useState('');

  const handleAddPatient = () => {
    Alert.prompt
      ? Alert.prompt('New Patient', 'Enter patient name:', (name) => {
          if (name?.trim()) addPatient(name.trim());
        })
      : (() => {
          // Android doesn't have Alert.prompt, use a simple workaround
          const name = ''; // Will use modal approach below
          Alert.alert('New Patient', 'Use the patient name field below to add a patient.');
        })();
  };

  const handleAddAllergy = () => {
    if (allergyText.trim()) {
      addAllergy(allergyText.trim());
      setAllergyText('');
      setShowAllergyInput(false);
    }
  };

  const handleDeleteAllergy = (id: number) => {
    Alert.alert('Remove Allergy', 'Remove this allergy?', [
      { text: 'Cancel', style: 'cancel' },
      { text: 'Remove', style: 'destructive', onPress: () => deleteAllergy(id) },
    ]);
  };

  const handleExport = async () => {
    const medications = patient.medications || [];
    const allergies = patient.allergies || [];

    if (medications.length === 0) {
      Alert.alert('No Medications', 'No medications to export.');
      return;
    }

    let text = `MEDICATION LIST\n`;
    text += `Patient: ${patient.name}\n`;
    text += `Date: ${new Date().toLocaleDateString()}\n\n`;

    if (allergies.length > 0) {
      text += `ALLERGIES:\n`;
      allergies.forEach((a) => (text += `  - ${a.name}\n`));
      text += '\n';
    }

    text += `CURRENT MEDICATIONS:\n${'='.repeat(50)}\n\n`;

    medications.forEach((med, i) => {
      text += `${i + 1}. ${med.name}\n`;
      text += `   Dosage: ${med.dosage}\n`;
      text += `   Frequency: ${med.frequency}\n`;
      if (med.doctor) text += `   Prescribing Doctor: Dr. ${med.doctor}\n`;
      if (med.reason) text += `   For: ${med.reason}\n`;
      if (med.refillDate) {
        const daysUntil = Math.ceil(
          (new Date(med.refillDate).getTime() - Date.now()) / (1000 * 60 * 60 * 24)
        );
        text += `   Next Refill: ${new Date(med.refillDate).toLocaleDateString()}`;
        if (daysUntil <= 7 && daysUntil >= 0) text += ` (${daysUntil} days)`;
        text += '\n';
      }
      text += '\n';
    });

    text += `\nGenerated by MedGuardian\n${new Date().toLocaleString()}\n`;

    try {
      if (Platform.OS === 'web') {
        await Share.share({ message: text });
      } else {
        const fileName = `meds-${patient.name.replace(/\s/g, '-')}-${new Date().toISOString().split('T')[0]}.txt`;
        const file = new File(Paths.cache, fileName);
        file.write(text);

        if (await Sharing.isAvailableAsync()) {
          await Sharing.shareAsync(file.uri, { mimeType: 'text/plain' });
        } else {
          await Share.share({ message: text });
        }
      }
    } catch (e) {
      // Fallback to basic share
      await Share.share({ message: text });
    }
  };

  // Patient selector with inline add
  const [newPatientName, setNewPatientName] = useState('');
  const [showNewPatient, setShowNewPatient] = useState(false);

  return (
    <View style={{ flex: 1 }}>
    <ScrollView style={styles.container} contentContainerStyle={styles.content}>
      {/* User Type Selector */}
      <View style={styles.userTypeRow}>
        <TouchableOpacity
          style={[styles.userTypeBtn, currentUserType === 'caregiver' && styles.userTypeBtnActive]}
          onPress={() => setCurrentUserType('caregiver')}
        >
          <Text style={[styles.userTypeBtnText, currentUserType === 'caregiver' && styles.userTypeBtnTextActive]}>
            Caregiver
          </Text>
        </TouchableOpacity>
        <TouchableOpacity
          style={[styles.userTypeBtn, currentUserType === 'provider' && styles.userTypeBtnActive]}
          onPress={() => setCurrentUserType('provider')}
        >
          <Text style={[styles.userTypeBtnText, currentUserType === 'provider' && styles.userTypeBtnTextActive]}>
            Provider
          </Text>
        </TouchableOpacity>
      </View>

      {/* Patient Selector */}
      <View style={styles.patientSection}>
        <ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.patientScroll}>
          {Object.entries(patients).map(([id, p]) => (
            <TouchableOpacity
              key={id}
              style={[styles.patientChip, id === currentPatient && styles.patientChipActive]}
              onPress={() => setCurrentPatient(id)}
            >
              <Text style={[styles.patientChipText, id === currentPatient && styles.patientChipTextActive]}>
                {p.name}
              </Text>
            </TouchableOpacity>
          ))}
          <TouchableOpacity style={styles.addPatientChip} onPress={() => setShowNewPatient(true)}>
            <Text style={styles.addPatientText}>+ Add</Text>
          </TouchableOpacity>
        </ScrollView>

        {showNewPatient && (
          <View style={styles.newPatientRow}>
            <TextInput
              style={styles.newPatientInput}
              placeholder="Patient name..."
              value={newPatientName}
              onChangeText={setNewPatientName}
              autoFocus
            />
            <TouchableOpacity
              style={styles.newPatientSave}
              onPress={() => {
                if (newPatientName.trim()) {
                  addPatient(newPatientName.trim());
                  setNewPatientName('');
                  setShowNewPatient(false);
                }
              }}
            >
              <Text style={styles.newPatientSaveText}>Add</Text>
            </TouchableOpacity>
            <TouchableOpacity onPress={() => { setShowNewPatient(false); setNewPatientName(''); }}>
              <Text style={{ color: '#a0aec0', fontSize: 16, marginLeft: 10 }}>Cancel</Text>
            </TouchableOpacity>
          </View>
        )}
      </View>

      {/* Allergies */}
      <View style={styles.allergySection}>
        <View style={styles.allergyHeader}>
          <Text style={styles.allergyTitle}>Allergies</Text>
          <TouchableOpacity style={styles.addAllergyBtn} onPress={() => setShowAllergyInput(true)}>
            <Text style={styles.addAllergyText}>+ Add Allergy</Text>
          </TouchableOpacity>
        </View>

        {showAllergyInput && (
          <View style={styles.allergyInputRow}>
            <TextInput
              style={styles.allergyInput}
              placeholder="Enter allergy..."
              value={allergyText}
              onChangeText={setAllergyText}
              autoFocus
              onSubmitEditing={handleAddAllergy}
            />
            <TouchableOpacity style={styles.allergyInputSave} onPress={handleAddAllergy}>
              <Text style={{ color: '#fff', fontWeight: '600' }}>Add</Text>
            </TouchableOpacity>
          </View>
        )}

        {(patient.allergies || []).length === 0 ? (
          <Text style={styles.emptyAllergy}>No allergies recorded</Text>
        ) : (
          patient.allergies.map((allergy) => (
            <View key={allergy.id} style={styles.allergyItem}>
              <Text style={styles.allergyName}>{allergy.name}</Text>
              <TouchableOpacity onPress={() => handleDeleteAllergy(allergy.id)}>
                <Text style={styles.allergyDelete}>x</Text>
              </TouchableOpacity>
            </View>
          ))
        )}
      </View>

      {/* Stats */}
      <StatsBar />

      {/* Alerts */}
      <AlertsList />

      {/* Schedule */}
      <ScheduleView medications={patient.medications} />

      {/* Medications List */}
      <View style={styles.medsHeader}>
        <Text style={styles.medsTitle}>Current Medications</Text>
        <TouchableOpacity style={styles.shareBtn} onPress={handleExport}>
          <Text style={styles.shareBtnText}>Share List</Text>
        </TouchableOpacity>
      </View>

      {patient.medications.length === 0 ? (
        <View style={styles.emptyState}>
          <Text style={styles.emptyText}>No medications added yet</Text>
          <Text style={styles.emptySubText}>
            Tap the + button below to add your first medication
          </Text>
        </View>
      ) : (
        patient.medications.map((med) => (
          <MedicationCard
            key={med.id}
            medication={med}
            interactions={interactions}
            allergyConflicts={allergyConflicts}
            onDelete={deleteMedication}
          />
        ))
      )}

      <Text style={styles.footer}>* This app displays general medication information from public databases. Not medical advice. Consult your healthcare provider.</Text>

      <View style={{ height: 80 }} />
    </ScrollView>

    {/* FAB */}
    <TouchableOpacity
      style={styles.fab}
      onPress={() => navigation.navigate('AddMedication')}
      activeOpacity={0.8}
    >
      <Text style={styles.fabText}>+</Text>
    </TouchableOpacity>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f5f7fa' },
  content: { padding: 16 },
  footer: { fontSize: 11, color: '#a0aec0', textAlign: 'center', marginTop: 20, paddingHorizontal: 10 },
  userTypeRow: { flexDirection: 'row', gap: 10, marginBottom: 16 },
  userTypeBtn: {
    flex: 1,
    padding: 12,
    borderWidth: 2,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  userTypeBtnActive: { backgroundColor: '#667eea', borderColor: '#667eea' },
  userTypeBtnText: { fontSize: 14, fontWeight: '600', color: '#4a5568' },
  userTypeBtnTextActive: { color: '#fff' },
  patientSection: { marginBottom: 16 },
  patientScroll: { flexDirection: 'row' },
  patientChip: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    backgroundColor: '#e2e8f0',
    marginRight: 8,
  },
  patientChipActive: { backgroundColor: '#667eea' },
  patientChipText: { fontSize: 14, color: '#4a5568' },
  patientChipTextActive: { color: '#fff', fontWeight: '600' },
  addPatientChip: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: '#cbd5e0',
    borderStyle: 'dashed',
  },
  addPatientText: { fontSize: 14, color: '#667eea' },
  newPatientRow: { flexDirection: 'row', alignItems: 'center', marginTop: 10 },
  newPatientInput: {
    flex: 1,
    borderWidth: 2,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    padding: 10,
    fontSize: 14,
    backgroundColor: '#fff',
  },
  newPatientSave: {
    backgroundColor: '#667eea',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginLeft: 8,
  },
  newPatientSaveText: { color: '#fff', fontWeight: '600' },
  allergySection: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 15,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#e2e8f0',
  },
  allergyHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  allergyTitle: { fontWeight: '600', fontSize: 14, color: '#4a5568' },
  addAllergyBtn: { backgroundColor: '#fc8181', paddingVertical: 6, paddingHorizontal: 12, borderRadius: 6 },
  addAllergyText: { color: '#fff', fontSize: 12, fontWeight: '600' },
  allergyInputRow: { flexDirection: 'row', marginBottom: 10 },
  allergyInput: {
    flex: 1,
    borderWidth: 2,
    borderColor: '#e2e8f0',
    borderRadius: 8,
    padding: 10,
    fontSize: 14,
  },
  allergyInputSave: {
    backgroundColor: '#fc8181',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginLeft: 8,
    justifyContent: 'center',
  },
  emptyAllergy: { color: '#a0aec0', fontStyle: 'italic', fontSize: 13 },
  allergyItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 8,
    backgroundColor: '#fff5f5',
    borderWidth: 1,
    borderColor: '#fc8181',
    borderRadius: 6,
    marginBottom: 6,
  },
  allergyName: { color: '#c53030', fontWeight: '600', fontSize: 14 },
  allergyDelete: { color: '#fc8181', fontSize: 18, paddingHorizontal: 8 },
  medsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  medsTitle: { fontSize: 18, fontWeight: '700', color: '#2d3748' },
  shareBtn: { backgroundColor: '#48bb78', paddingVertical: 8, paddingHorizontal: 16, borderRadius: 8 },
  shareBtnText: { color: '#fff', fontSize: 14, fontWeight: '600' },
  emptyState: { alignItems: 'center', padding: 40 },
  emptyText: { fontSize: 16, color: '#a0aec0', marginBottom: 8 },
  emptySubText: { fontSize: 14, color: '#cbd5e0', textAlign: 'center' },
  fab: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#667eea',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
  },
  fabText: { color: '#fff', fontSize: 28, fontWeight: '600', marginTop: -2 },
});
